= Backend/Infra Services Adapters Libraries

The adapter serves backend/infra system services as a library.

You can use the library just giving the http client with your suitable configuration.

The library handles the adapter integration layer works such as data modeling, exception handling, http rest/soap protocol complexities.

*IMPORTANT NOTE:* The doc should be updated when doing implementation.

== Advantages

* Data Adapter Response Model pattern utilization (re-usability)
* REST/SOAP Exception Handling pattern utilization (re-usability)
* Layering/Abstraction of integration
* Standardizing integrations
* Increase development productivity
* Please add any one of them when using…

== Libraries

There are two levels of library layers for now.

=== micro-integration

The top of the integration layer of the microservice.
There is no dependency without JDK.
The layer consists of interfaces, models, utilities and related stuffs.

=== micro-middleware

The second layer of the integration architecture.
It consists of the abstractions of integration parts such as http client, spring-ws-core, javax validation, apache common utility libs.

== Protocols

=== REST

Apache HttpClient 5

=== SOAP

==== Generation (WSDL2JAVA)

One of following optionals is for generation. (Choose one of them what your comfort-zone is)

----
Apache CXF (optional)
AXIS (optional)
GRADLE JAXB Plugin (Optional)
JDK 17
----

Stubs are generated via apache cxf library using sh script or gradle task.

You can find the example shell scripts under the files/scripts directory.
ws-country-client is the example of the jaxb generated.

==== Http Client

----
Apache HttpClient 5
----

==== WS Layer

----
Spring-ws-core
Apache HttpClient 5
----

== External Adapter (Backend service) Response Pattern

The generic code of the segmentation should be finalized.

The codes in the templates below are given as an example.

[source,json]
----
{
  "status" : {
   "code" : "0",
    "message" : "Success"
  },
  "data" : {
    "T" : {
      //Any Object of server success response
    }
  }
}

----

== Exception Cases

There are three phases to get error.

=== client exception

[source,json]
----
{
  "status": {
    "code": "4000",
    "message": "Adapter Client Message" // fixed message
  }
}

----

=== server exception

code : it is originated from server response
message : it is originated from server response

[source,json]
----
{
  "status": {
    "code": "5000",
    "message": "Server Message" //get from server
  }
}
----

=== client exception after server response handling

[source,json]
----
{
  "status": {
    "code": "4500",
    "message": "Server Response Message Client Handling Exception Message" // fixed message
  }
}
----
