
config-manager:
  enabled: true
  source: properties
  reload:
    enabled: true
    trigger: cron
    cron-expression: '0/2 * * * * ?'
  properties:
    property-files: classpath:settings.properties
